[pre-commit]
parallel = true

[pre-commit.commands.toml]
glob = "*.toml"
run = "pnpm taplo check {staged_files}"



[pre-commit.commands.format]
glob = "*.{tsx,ts,js,jsx,css,json}"
run = "pnpm prettier --write {staged_files} && git update-index --again"

[commit-msg.commands.commitlint]
run = "pnpm commitlint --edit $1"
